# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contents/ui/config.ui'
#
# Created: Wed Jun 29 00:19:46 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_cfgDialog(object):
	def setupUi(self, cfgDialog):
		cfgDialog.setObjectName("cfgDialog")
		cfgDialog.setWindowModality(QtCore.Qt.NonModal)
		cfgDialog.resize(270, 260)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(cfgDialog.sizePolicy().hasHeightForWidth())
		cfgDialog.setSizePolicy(sizePolicy)
		cfgDialog.setMinimumSize(QtCore.QSize(270, 260))
		self.formLayoutWidget = QtGui.QWidget(cfgDialog)
		self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 271, 261))
		self.formLayoutWidget.setObjectName("formLayoutWidget")
		self.gridLayout = QtGui.QGridLayout(self.formLayoutWidget)
		self.gridLayout.setObjectName("gridLayout")
		self.programLabel = QtGui.QLabel(self.formLayoutWidget)
		self.programLabel.setObjectName("programLabel")
		self.gridLayout.addWidget(self.programLabel, 0, 0, 1, 2)
		self.latLabel = QtGui.QLabel(self.formLayoutWidget)
		self.latLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
		self.latLabel.setObjectName("latLabel")
		self.gridLayout.addWidget(self.latLabel, 1, 0, 1, 2)
		self.lonLabel = QtGui.QLabel(self.formLayoutWidget)
		self.lonLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
		self.lonLabel.setObjectName("lonLabel")
		self.gridLayout.addWidget(self.lonLabel, 2, 0, 1, 2)
		self.smoothCheckBox = QtGui.QCheckBox(self.formLayoutWidget)
		self.smoothCheckBox.setObjectName("smoothCheckBox")
		self.gridLayout.addWidget(self.smoothCheckBox, 5, 0, 1, 4)
		self.dayTmpLabel = QtGui.QLabel(self.formLayoutWidget)
		self.dayTmpLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
		self.dayTmpLabel.setObjectName("dayTmpLabel")
		self.gridLayout.addWidget(self.dayTmpLabel, 3, 0, 1, 2)
		self.nightTmpLabel = QtGui.QLabel(self.formLayoutWidget)
		self.nightTmpLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
		self.nightTmpLabel.setObjectName("nightTmpLabel")
		self.gridLayout.addWidget(self.nightTmpLabel, 4, 0, 1, 2)
		self.modeLabel = QtGui.QLabel(self.formLayoutWidget)
		self.modeLabel.setObjectName("modeLabel")
		self.gridLayout.addWidget(self.modeLabel, 6, 0, 1, 2)
		self.autolaunchCheckBox = QtGui.QCheckBox(self.formLayoutWidget)
		self.autolaunchCheckBox.setObjectName("autolaunchCheckBox")
		self.gridLayout.addWidget(self.autolaunchCheckBox, 8, 0, 1, 4)
		self.gammaBoxR = QtGui.QDoubleSpinBox(self.formLayoutWidget)
		self.gammaBoxR.setMinimum(0.1)
		self.gammaBoxR.setMaximum(10.0)
		self.gammaBoxR.setSingleStep(0.1)
		self.gammaBoxR.setObjectName("gammaBoxR")
		self.gridLayout.addWidget(self.gammaBoxR, 7, 1, 1, 1)
		self.gammaLabel = QtGui.QLabel(self.formLayoutWidget)
		self.gammaLabel.setObjectName("gammaLabel")
		self.gridLayout.addWidget(self.gammaLabel, 7, 0, 1, 1)
		self.gammaBoxG = QtGui.QDoubleSpinBox(self.formLayoutWidget)
		self.gammaBoxG.setMinimum(0.1)
		self.gammaBoxG.setMaximum(10.09)
		self.gammaBoxG.setSingleStep(0.1)
		self.gammaBoxG.setObjectName("gammaBoxG")
		self.gridLayout.addWidget(self.gammaBoxG, 7, 2, 1, 1)
		self.gammaBoxB = QtGui.QDoubleSpinBox(self.formLayoutWidget)
		self.gammaBoxB.setMinimum(0.1)
		self.gammaBoxB.setMaximum(10.0)
		self.gammaBoxB.setSingleStep(0.1)
		self.gammaBoxB.setObjectName("gammaBoxB")
		self.gridLayout.addWidget(self.gammaBoxB, 7, 3, 1, 1)
		self.programComboBox = QtGui.QComboBox(self.formLayoutWidget)
		self.programComboBox.setObjectName("programComboBox")
		self.programComboBox.addItem("")
		self.programComboBox.setItemText(0, "f.lux")
		self.programComboBox.addItem("")
		self.programComboBox.setItemText(1, "Redshift")
		self.gridLayout.addWidget(self.programComboBox, 0, 2, 1, 2)
		self.latBox = QtGui.QDoubleSpinBox(self.formLayoutWidget)
		self.latBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
		self.latBox.setDecimals(1)
		self.latBox.setMinimum(-190.0)
		self.latBox.setMaximum(190.0)
		self.latBox.setSingleStep(0.1)
		self.latBox.setObjectName("latBox")
		self.gridLayout.addWidget(self.latBox, 1, 2, 1, 2)
		self.lonBox = QtGui.QDoubleSpinBox(self.formLayoutWidget)
		self.lonBox.setDecimals(1)
		self.lonBox.setMinimum(-180.0)
		self.lonBox.setMaximum(180.0)
		self.lonBox.setSingleStep(0.1)
		self.lonBox.setObjectName("lonBox")
		self.gridLayout.addWidget(self.lonBox, 2, 2, 1, 2)
		self.dayTmpBox = QtGui.QSpinBox(self.formLayoutWidget)
		self.dayTmpBox.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
		self.dayTmpBox.setMaximum(15000)
		self.dayTmpBox.setObjectName("dayTmpBox")
		self.gridLayout.addWidget(self.dayTmpBox, 3, 2, 1, 2)
		self.nightTmpBox = QtGui.QSpinBox(self.formLayoutWidget)
		self.nightTmpBox.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
		self.nightTmpBox.setMaximum(15000)
		self.nightTmpBox.setObjectName("nightTmpBox")
		self.gridLayout.addWidget(self.nightTmpBox, 4, 2, 1, 2)
		self.modeComboBox = QtGui.QComboBox(self.formLayoutWidget)
		self.modeComboBox.setObjectName("modeComboBox")
		self.modeComboBox.addItem("")
		self.modeComboBox.addItem("")
		self.gridLayout.addWidget(self.modeComboBox, 6, 2, 1, 2)

		self.retranslateUi(cfgDialog)
		QtCore.QMetaObject.connectSlotsByName(cfgDialog)

	def retranslateUi(self, cfgDialog):
		self.programLabel.setText(QtGui.QApplication.translate("cfgDialog", "Program", None, QtGui.QApplication.UnicodeUTF8))
		self.latLabel.setText(QtGui.QApplication.translate("cfgDialog", "Latitude", None, QtGui.QApplication.UnicodeUTF8))
		self.lonLabel.setText(QtGui.QApplication.translate("cfgDialog", "Longitude", None, QtGui.QApplication.UnicodeUTF8))
		self.smoothCheckBox.setToolTip(QtGui.QApplication.translate("cfgDialog", "Check this if you want smooth transitions", None, QtGui.QApplication.UnicodeUTF8))
		self.smoothCheckBox.setText(QtGui.QApplication.translate("cfgDialog", "Smooth transition", None, QtGui.QApplication.UnicodeUTF8))
		self.dayTmpLabel.setText(QtGui.QApplication.translate("cfgDialog", "Day temperature", None, QtGui.QApplication.UnicodeUTF8))
		self.nightTmpLabel.setText(QtGui.QApplication.translate("cfgDialog", "Night temperature", None, QtGui.QApplication.UnicodeUTF8))
		self.modeLabel.setText(QtGui.QApplication.translate("cfgDialog", "Mode", None, QtGui.QApplication.UnicodeUTF8))
		self.autolaunchCheckBox.setToolTip(QtGui.QApplication.translate("cfgDialog", "Launch at start-up", None, QtGui.QApplication.UnicodeUTF8))
		self.autolaunchCheckBox.setText(QtGui.QApplication.translate("cfgDialog", "Auto-launch", None, QtGui.QApplication.UnicodeUTF8))
		self.gammaBoxR.setToolTip(QtGui.QApplication.translate("cfgDialog", "Gamma correction (Red)", None, QtGui.QApplication.UnicodeUTF8))
		self.gammaLabel.setToolTip(QtGui.QApplication.translate("cfgDialog", "Additional gamma correction (default is 1:1:1)", None, QtGui.QApplication.UnicodeUTF8))
		self.gammaLabel.setText(QtGui.QApplication.translate("cfgDialog", "Gamma (RGB)", None, QtGui.QApplication.UnicodeUTF8))
		self.gammaBoxG.setToolTip(QtGui.QApplication.translate("cfgDialog", "Gamma correction (Green)", None, QtGui.QApplication.UnicodeUTF8))
		self.gammaBoxB.setToolTip(QtGui.QApplication.translate("cfgDialog", "Gamma correction (Blue)", None, QtGui.QApplication.UnicodeUTF8))
		self.latBox.setSuffix(QtGui.QApplication.translate("cfgDialog", "º", None, QtGui.QApplication.UnicodeUTF8))
		self.lonBox.setSuffix(QtGui.QApplication.translate("cfgDialog", "º", None, QtGui.QApplication.UnicodeUTF8))
		self.dayTmpBox.setToolTip(QtGui.QApplication.translate("cfgDialog", "Day temperature. Neutral is 6500", None, QtGui.QApplication.UnicodeUTF8))
		self.dayTmpBox.setSuffix(QtGui.QApplication.translate("cfgDialog", "ºK", None, QtGui.QApplication.UnicodeUTF8))
		self.nightTmpBox.setToolTip(QtGui.QApplication.translate("cfgDialog", "Night temperature. Recommended is 4500 for Redshift and 3400 for F.lux", None, QtGui.QApplication.UnicodeUTF8))
		self.nightTmpBox.setSuffix(QtGui.QApplication.translate("cfgDialog", "ºK", None, QtGui.QApplication.UnicodeUTF8))
		self.modeComboBox.setToolTip(QtGui.QApplication.translate("cfgDialog", "Video mode", None, QtGui.QApplication.UnicodeUTF8))
		self.modeComboBox.setItemText(0, QtGui.QApplication.translate("cfgDialog", "randr", None, QtGui.QApplication.UnicodeUTF8))
		self.modeComboBox.setItemText(1, QtGui.QApplication.translate("cfgDialog", "vidmode", None, QtGui.QApplication.UnicodeUTF8))

